#!/bin/bash
universe = vanilla
log = /home/mzheng54/MaxD/Test/log/job_$(Cluster)_$(Process).log
error = /home/mzheng54/MaxD/Test/log/job_$(Cluster)_$(Process).err
output = /home/mzheng54/MaxD/Test/log/job_$(Cluster)_$(Process).out
executable = test.sh
arguments = $(a) $(b) $(c) $(d)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = http://proxy.chtc.wisc.edu/SQUID/chtc/python38.tar.gz,/home/mzheng54/packages.tar.gz,test_dir.py,parameter.txt
request_cpus = 1
request_memory = 2GB
request_disk = 1GB
max_idle = 5000

queue 1 a,b,c,d from parameter.txt 
